### ISSUE TITLE
Breaking change made in a patch version

### ISSUE THREAD

**Issue by Poliziano** [rvagg/jsonist#13]
The latest update from 2.1.0 to 2.1.1 has changed usages of 'var' to 'let', which is a breaking change for anyone using node versions < 6. This package is not a direct dependency of ours and therefore we do not control the version. Our version of node _cannot_ be upgraded for legacy reasons, and we are now unable to redeploy our server. 

Could you please publish a new patch version which reverts to 'var', and republish your latest version as either a minor or major version.

**Comment by rvagg** [comment]
thanks for letting me know, published jsonist@2.1.2
