### ISSUE TITLE
Non-JSON 404s throw Syntax errors

### ISSUE THREAD

**Issue by geelen** [rvagg/jsonist#7]
If an endpoint is expecting JSON but hits, say, a 404 returning text/plain, the JSON is still attempted to be parsed and a Syntax Error is returned as the `err` to the callback. But you may want to handle that differently to an _actual_ syntax error. I suggest the response code & mime-type should be checked before the body is parsed, and maybe return a `jsonist.NOT_JSON_ERROR` instead of a `SyntaxError` so we can differentiate the classes of failure.

Current output for a http server sending back text/plain as "Not Found":
![image](https://cloud.githubusercontent.com/assets/23264/8402677/ca960c26-1e80-11e5-9060-e6862deb75b1.png)

**Comment by rvagg** [comment]
@geelen good point, don't suppose you want to PR that? perhaps the easiest path is to simply try/catch and deal with the special case inside the catch.

**Comment by geelen** [comment]
I think actually pulling the `response` and only trying to parse JSON if it's a `200` and a `application/json`. That way, if you *do* actually send back invalid JSON, your app explodes :fire:

Haven't even dug into the source but I may get a chance tomorrow and I'll flick a PR if so.

**Comment by rvagg** [comment]
see https://github.com/rvagg/jsonist#error-handling-and-bad-json-responses, hopefully this works OK
